services:
  # Applications
  #  assistant-service:
  #    image: assistant-service:0.0.1-SNAPSHOT
  #    container_name: assistant-service
  #    ports:
  #      - "9001:9001"
  #      - "8001:8001"
  #    depends_on:
  #      - fluent-bit
  #      - tempo
  #    environment:
  #      - BPL_DEBUG_ENABLED=true
  #      - BPL_DEBUG_PORT=8001
  #      - OPENAI_BASE_URL=http://host.docker.internal:11434
  #      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.20.0.jar
  #      - OTEL_SERVICE_NAME=assistant-service
  #      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
  #      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  #      - OTEL_METRICS_EXPORTER=none
  #      - OTEL_LOGS_EXPORTER=none
  #    logging:
  #      driver: fluentd
  #      options:
  #        fluentd-address: 127.0.0.1:24224
  catalog-service:
    image: catalog-service:0.0.1-SNAPSHOT
    container_name: catalog-service
    ports:
      - "9002:9002"
      - "8002:8002"
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - BPL_JVM_THREAD_COUNT=50
      - DB_USER=user
      - DB_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-postgres:5432/storedb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
    depends_on:
      - store-postgres

  # Data services
  store-postgres:
    image: postgres:latest
    container_name: store-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - store-postgres:/var/lib/postgresql
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Observability
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#
#  grafana:
#    image: grafana/grafana-oss:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-storage:/var/lib/grafana
#      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
#      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
#      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    depends_on:
#      - loki
#      - prometheus
#      - tempo
#
#  loki:
#    image: grafana/loki:latest
#    container_name: loki
#    ports:
#      - "3100:3100"
#    depends_on:
#      - fluent-bit
#
#  fluent-bit:
#    image: grafana/fluent-bit-plugin-loki:latest
#    container_name: fluent-bit
#    ports:
#      - "24224:24224"
#    environment:
#      - LOKI_URL=http://loki:3100/loki/api/v1/push
#    volumes:
#      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#
#  tempo:
#    image: grafana/tempo:latest
#    container_name: tempo
#    command: -config.file=/etc/tempo-config.yaml
#    ports:
#      - "3200:3200"
#      - "4317:4317"
#      - "4318:4318"
#    volumes:
#      - ./observability/tempo/tempo.yml:/etc/tempo-config.yaml

volumes:
  store-postgres: { }
  #grafana-storage: