# Configuration file version
apiVersion: 1

# List of datasources to delete before adding or updating
deleteDatasources:
  - name: Prometheus

# Mark provisioned data sources for deletion if they are no longer in provision file
# It take no effect if data sources are already listed in deleteDatasources
prune: true

# List of datasources to provision or update
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
